config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :events
  get 'home/index'
  get 'my_events', to: 'events#my_events'
  get 'search', to: 'events#search'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'events#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :user
  has_one :event_location, dependent: :destroy
  accepts_nested_attributes_for :event_location
  delegate :address, to: :event_location, allow_nil: true
  validates :name, presence: true
  validates :start_date_time, presence: true
  validates :end_date_time, presence: true
end

app/models/event_location.rb
# frozen_string_literal: true

class EventLocation < ApplicationRecord
  belongs_to :event
  validates :address, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include Draper::Decoratable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  include EventsHelper
  before_action :event, only: %i[show edit update destroy]

  # returns selfncreated events
  def my_events
    @events = current_user.events
  end

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show; end

  # GET /events/new
  def new
    @event = Event.new
    @event.build_event_location
  end

  # GET /events/1/edit
  def edit; end

  def create
    @event = EventCreator.call(event_params)

    if @event.present?
      redirect_to event_url(@event), notice: 'Event was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  rescue StandardError => e
    flash[:alert] = "Error: #{e.message}"
    redirect_to new_event_url
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    if EventUpdater.call(event_params, @event)
      redirect_to event_url(@event), notice: 'Event was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  rescue StandardError => e
    flash[:alert] = "Error: #{e.message}"
    redirect_to edit_event_url(@event.id)
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
    end
  rescue StandardError
    redirect_to events_url, alert: 'An error occurred while destroying the event.'
  end

  def search
    @events = EventSearch.call(params[:search])
  rescue StandardError => e
    @events = []
    flash[:alert] = "An error occurred while searching for events: #{e.message}"
    redirect_to events_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def event
    @event ||= Event.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to events_url, alert: 'Event not found.'
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:name, :description, :user_id, :start_date_time, :end_date_time,
                                  event_location_attributes: {})
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
  # validate :end_date_greater_than_start_date
  def schedule(start_date_time, end_date_time)
    start_date_time = start_date_time.in_time_zone(Time.zone)
    end_date_time = end_date_time.in_time_zone(Time.zone)
    "#{start_date_time.strftime('%d/%m/%Y %H:%M')} - #{end_date_time.strftime('%d/%m/%Y %H:%M')}"
  end
end

app/views/events/_event.html.erb
<%# Include EventsHelper or ApplicationHelper %>
<%# include EventsHelper %>
<%# include ApplicationHelper %>

<div id="<%= dom_id event %>" class="p-3 col-md-4">
  <div class="card" style="width: 22rem;">
    <div class="card-body">
      <h5 class="card-title"><%= event.name %></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= schedule(event.start_date_time, event.end_date_time) %></h6>
      <p class="card-text py-3" style="max-height: 100px; overflow: hidden;"> <!-- Added py-3 class here -->
        <%= truncate(event.description, length: 30, separator: ' ', omission: '...') %>
      </p>
      <a href="#" class="card-link"><%= link_to "View", event_path(event.id) %></a>
      <% if event.user_id == current_user.id %>
        <a href="#" class="card-link"><%= link_to "Edit", edit_event_path(event.id) %></a>
      <% end %>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_with(model: event, class: "py-3", data: {controller: "locations", action: "google-maps-callback@window->locations#initMap" }) do |f| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %> 

  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class='row'>
    <div class="col-md-6">
      <div class='row'>
        <div class="mb-3"> 
          <%= f.label :title, class: "form-label" %>
          <%= f.text_field :name, autofocus: true, autocomplete: "name", class: 'form-control', required: true %>
        </div> 
      </div>

      <div class='row'>
        <div class="mb-3">
          <%= f.label :description, class: "form-label" %>
          <%= f.text_area :description, autofocus: true, autocomplete: "description", class: 'form-control' %>
        </div>
      </div>
      
      <%= f.fields_for(:event_location) do |el| %>
        <div class='row'>
          <div class="mb-3">
            <%= el.label :venue, class: "form-label" %>
            <%= el.search_field :address, autofocus: true, autocomplete: "address", class: 'form-control', required: true, data: { target: 'locations.field'} %>
          </div>
        </div>

        <div class='row'>
          <div class="col-md-6 mb-3">
            <%= el.label :latitude, class: "form-label" %>
            <%= el.text_field :lat, autofocus: true, autocomplete: "latitude", class: 'form-control', required: true, data: { target: 'locations.latitude'} %>
          </div>

          <div class="col-md-6 mb-3">
            <%= el.label :longitude, class: "form-label" %>
            <%= el.text_field :lng, autofocus: true, autocomplete: "longitude", class: 'form-control', required: true, data: { target: 'locations.longitude'} %>
          </div>
        </div>
      <% end %>

      <div class='row'>
        <div class="col-md-6 mb-3">
          <%= f.label :start_time, class: "form-label" %>
          <%= f.datetime_field :start_date_time, autofocus: true, autocomplete: "start_date_time", required: true, class: 'form-control', min: DateTime.now, step: 'any' %>
        </div>
        <div class="col-md-6 mb-3">
          <%= f.label :end_time, class: "form-label" %>
          <%= f.datetime_field :end_date_time, autofocus: true, autocomplete: "end_date_time", required: true, class: 'form-control', min: DateTime.now, step: 'any' %>
        </div>
      </div>
    </div>

    <div class="col-md-6 pt-4">
      <div data-locations-target= "map" style="height:400px"></div>
    </div>
  </div>
  <%= f.submit class: "btn btn-primary mb-4"%>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", event: @event %>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>All Events</h1>

<div id="events" class="row">
  <% @events.each do |event| %>
    <%= render event %>
  <% end %>
</div>

app/views/events/my_events.html.erb
<p style="color: green"><%= notice %></p>

<h1 >My Events</h1>

<div id="events" class="row">
  <% @events.each do |event| %>
    <%= render event %>
  <% end %>
</div>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render "form", event: @event %>

<% if @event.errors[:end_date_time].any? %>
  <div class="alert alert-danger">
    <%= @event.errors[:end_date_time].first %>
  </div>
<% end %>

<br>

<div>
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/search.html.erb
<p style="color: green"><%= notice %></p>

<h1>Search results of: <%= params[:search]%></h1>

<div id="events" class="row">
  <% if @events.present? %>
    <% @events.each do |event| %>
      <%= render event %>
    <% end %>
  <% else %>
    <p><h3>No results found</h3></p>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-5 py-5 offset-md-1">
      <div class="row mb-3">
        <div class="col-md-6">
          Event Title:
        </div>
        <div class="col-md-6">
          <%= @event.name %>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-md-6">
          Event description:
        </div>
        <div class="col-md-6">
          <%= @event.description%>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-md-6">
          Schedule:
        </div>
        <div class="col-md-6">
        <h6 class="card-subtitle mb-2 text-muted"><%= schedule(@event.start_date_time, @event.end_date_time) %></h6>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-md-6">
          Venue:
        </div>
        <div class="col-md-6">
          <%= @event.address %>
        </div>
      </div>

      <div class="row mb-3">
        <% if @event.user_id == current_user.id %>
        <div class="col-md-6">
          <%= link_to 'Edit Event', edit_event_path(@event), class: 'btn btn-outline-primary my-3' %>
        </div>
        <div class="col-md-6">
          <%= button_to 'Delete Event', event_path(@event),  method: :delete,class: 'btn btn-outline-danger my-3' %>
        </div>
        <% end %>
      </div>
    </div>

    <div class="col-md-6" data-controller="events">
      <div class="col-md-6">
        <input type="hidden" data-events-target="lat" value="<%= @event.event_location&.lat.to_f %>">
        <input type="hidden" data-events-target="lng" value="<%= @event.event_location&.lng.to_f %>">
      </div>
      <div class="col-md-6" data-events-target="direction" style="height: 400px">

      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close" data-controller="modal" data-action="click->modal#close:prevent">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger' >
        <button type="button" class="close" data-dismiss="alert" aria-label="Close" data-controller="modal" data-action="click->modal#close:prevent">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <%= link_to 'Event Management App', root_path, class: 'navbar-brand' %>
        <% if current_user %> 
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
          
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item <%= 'active' if request.path == my_events_path %>">
                        <%= link_to 'My Events', my_events_path, class: 'nav-link' %>
                    </li>
                    <li class="nav-item <%= 'active' if request.path == events_path %>">
                        <%= link_to 'All Events', events_path, class: 'nav-link' %>
                    </li>
                </ul>
          
                <%= form_with url: search_path, method: :get, class: 'form-inline my-2 my-lg-0 row py-7 mx-auto col-10 col-md-8 col-lg-6' do |f|%>
                  <div class="col-md-9">
                    <%= f.text_field :search, autocomplete: "off", placeholder: 'Search by title or description ..', class: "form-control mr-sm-2" %>
                  </div>
                   <div class="col-md-3">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                   </div>
                <% end %>
                
                <ul class="navbar-nav mr-auto px-4">
                    <li class="nav-item <%= 'active' if request.path == my_events_path %>">
                        <%= link_to 'Create Event', new_event_path, class: 'btn btn-outline-primary my-3' %>
                    </li>
                </ul>

                <ul class='navbar-nav ml-auto row'>
                    <li class='nav-item user-name col-md-6 pt-2'>
                        <%= fa_icon 'user' %> <%= current_user.decorate.full_name %> 
                    </li>
                    <li class='nav-item col-md-6'>
                        <%= button_to("Logout", destroy_user_session_path,
                            class: "btn btn-danger logout-button", method: :delete)%>
                    </li>
                </ul>

            </div>
        <% end %>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.credentials.dig(:google_api_key) %>&libraries=places&callback=initMap" async defer data-turbolinks-eval="false"></script>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container p-3">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>